Repository df-mc/dragonfly, pull requests merged in 2020-07, with the labels that each got.

#29 Beacon
  dragonfly/block/beacon.go
  dragonfly/block/block.go
  dragonfly/block/coal_block.go
  dragonfly/block/diamond_block.go
  dragonfly/block/emerald_block.go
  dragonfly/block/gold_block.go
  dragonfly/block/hashes.go
  dragonfly/block/iron_block.go
  dragonfly/block/netherite_block.go
  dragonfly/block/register.go
  dragonfly/entity/effect.go
  dragonfly/entity/effect/absorption.go
  dragonfly/entity/effect/blindness.go
  dragonfly/entity/effect/conduit_power.go
  dragonfly/entity/effect/effect.go
  dragonfly/entity/effect/fatal_poison.go
  dragonfly/entity/effect/haste.go
  dragonfly/entity/effect/health_boost.go
  dragonfly/entity/effect/hunger.go
  dragonfly/entity/effect/instant_damage.go
  dragonfly/entity/effect/instant_health.go
  dragonfly/entity/effect/invisibility.go
  dragonfly/entity/effect/jump_boost.go
  dragonfly/entity/effect/levitation.go
  dragonfly/entity/effect/mining_fatigue.go
  dragonfly/entity/effect/nausea.go
  dragonfly/entity/effect/night_vision.go
  dragonfly/entity/effect/poison.go
  dragonfly/entity/effect/regeneration.go
  dragonfly/entity/effect/resistance.go
  dragonfly/entity/effect/saturation.go
  dragonfly/entity/effect/slow_falling.go
  dragonfly/entity/effect/slowness.go
  dragonfly/entity/effect/speed.go
  dragonfly/entity/effect/strength.go
  dragonfly/entity/effect/water_breathing.go
  dragonfly/entity/effect/weakness.go
  dragonfly/entity/effect/wither.go
  dragonfly/internal/world_internal/beacon.go
  dragonfly/item/diamond.go
  dragonfly/item/item.go
  dragonfly/item/register.go
  dragonfly/item/stack.go
  dragonfly/player/player.go
  dragonfly/session/handler_item_stack_request.go
  dragonfly/session/player.go
  dragonfly/session/world.go
  dragonfly/world/block.go
  dragonfly/world/item.go
  dragonfly/world/world.go
Labels: ready for review

#33 Implemented trapdoors
  dragonfly/block/hashes.go
  dragonfly/block/register.go
  dragonfly/block/trapdoor.go
Labels: ready for review

#37 Implement Coral Blocks
  dragonfly/block/coral/coral.go
  dragonfly/block/coral_block.go
  dragonfly/block/hashes.go
  dragonfly/block/register.go
Labels: awaiting changes

#38 Implemented Doors
  dragonfly/block/door.go
  dragonfly/block/hashes.go
  dragonfly/block/model/door.go
  dragonfly/block/register.go
Labels: ready for review

#36 Control Server-Side XBOX Live Authentication
  config.toml
  dragonfly/config.go
  dragonfly/player/player.go
  dragonfly/server.go
  dragonfly/session/controllable.go
Labels: done, help wanted

#34 Added Lapis Lazuli and Lapis Lazuli Block
  dragonfly/block/hashes.go
  dragonfly/block/lapis_block.go
  dragonfly/block/register.go
  dragonfly/item/lapis_lazuli.go
  dragonfly/item/register.go
Labels: awaiting changes

#26 [WIP] Implement stained glass blocks and panes
  dragonfly/block/glass_pane.go
  dragonfly/block/hashes.go
  dragonfly/block/model.go
  dragonfly/block/model/thin.go
  dragonfly/block/register.go
  dragonfly/block/stained_glass.go
  dragonfly/block/stained_glass_pane.go
  dragonfly/block/wood_slab.go
  dragonfly/item/emerald.go
  dragonfly/item/gold_ingot.go
  dragonfly/item/iron_ingot.go
  dragonfly/item/netherite_ingot.go
Labels: awaiting changes

#35 Added glowstone, glowstone dust, and glowstone dust drop percentages.
  dragonfly/block/glowstone.go
  dragonfly/block/hashes.go
  dragonfly/block/register.go
  dragonfly/item/glowstone_dust.go
  dragonfly/item/register.go
Labels: awaiting changes

#39 Added assortment of decorative blocks
  dragonfly/block/bone_block.go
  dragonfly/block/clay.go
  dragonfly/block/end_stone.go
  dragonfly/block/fire/fire.go
  dragonfly/block/hashes.go
  dragonfly/block/lantern.go
  dragonfly/block/model/lantern.go
  dragonfly/block/netherrack.go
  dragonfly/block/register.go
  dragonfly/item/clay_ball.go
  dragonfly/item/register.go
Labels: done

#40 Implemented pumpkins/shears
  dragonfly/block/hashes.go
  dragonfly/block/lit_pumpkin.go
  dragonfly/block/pumpkin.go
  dragonfly/block/register.go
  dragonfly/internal/item_internal/item.go
  dragonfly/item/inventory/armour.go
  dragonfly/item/register.go
  dragonfly/item/shears.go
Labels: awaiting changes

#43 Add End Bricks & End Brick Stairs
  dragonfly/block/end_brick_stairs.go
  dragonfly/block/end_bricks.go
  dragonfly/block/hashes.go
  dragonfly/block/register.go
Labels: ready for review

#45 Implemented fence gates
  dragonfly/block/hashes.go
  dragonfly/block/model/fence_gate.go
  dragonfly/block/register.go
  dragonfly/block/wood/wood.go
  dragonfly/block/wood_door.go
  dragonfly/block/wood_fence_gate.go
  dragonfly/block/wood_trapdoor.go
  dragonfly/entity/physics/aabb.go
Labels: done

#46 Added various ores
  dragonfly/block/ancient_debris.go
  dragonfly/block/break_info.go
  dragonfly/block/coal_ore.go
  dragonfly/block/diamond_ore.go
  dragonfly/block/emerald_ore.go
  dragonfly/block/gold_ore.go
  dragonfly/block/hashes.go
  dragonfly/block/iron_ore.go
  dragonfly/block/lapis_ore.go
  dragonfly/block/nether_gold_ore.go
  dragonfly/block/register.go
  dragonfly/item/coal.go
  dragonfly/item/gold_nugget.go
  dragonfly/item/register.go
Labels: awaiting review

#51 Implemented block picking
  dragonfly/item/inventory/inventory.go
  dragonfly/player/handler.go
  dragonfly/player/player.go
  dragonfly/session/controllable.go
  dragonfly/session/handler_block_pick_request.go
  dragonfly/session/player.go
  dragonfly/session/session.go
Labels: awaiting review

#52 Implemented cocoa beans
  dragonfly/block/cocoa_bean.go
  dragonfly/block/hashes.go
  dragonfly/block/model/cocoa_bean.go
  dragonfly/block/register.go
Labels: awaiting review

#57 Implemented item dropping
  dragonfly/entity/item.go
  dragonfly/entity/physics/aabb.go
  dragonfly/item/stack.go
  dragonfly/player/handler.go
  dragonfly/player/player.go
  dragonfly/session/controllable.go
  dragonfly/session/handler_inventory_transaction.go
  dragonfly/session/handler_item_stack_request.go
Labels: awaiting review
