Repository df-mc/dragonfly, pull requests merged in 2020-08, with the labels that each got.

#59 Added Iron Bars
  dragonfly/block/hashes.go
  dragonfly/block/iron_bars.go
  dragonfly/block/register.go
Labels: awaiting changes

#62 Added Nether quartz, Quartz blocks, Quartz ore
  dragonfly/block/hashes.go
  dragonfly/block/quartz_block.go
  dragonfly/block/quartz_bricks.go
  dragonfly/block/quartz_ore.go
  dragonfly/block/register.go
  dragonfly/item/nether_quartz.go
  dragonfly/item/register.go
Labels: done

#65 Implemented block gravity
  dragonfly/block/block.go
  dragonfly/block/concrete_powder.go
  dragonfly/block/gravel.go
  dragonfly/block/hashes.go
  dragonfly/block/register.go
  dragonfly/block/sand.go
  dragonfly/entity/falling_block.go
  dragonfly/internal/entity_internal/entity.go
  dragonfly/item/flint.go
  dragonfly/item/register.go
  dragonfly/session/player.go
  dragonfly/session/world.go
Labels: awaiting review

#58 retrieve player instance if you dont know their uuid
  dragonfly/server.go
Labels: awaiting review

#64 Implemented potions
  dragonfly/block/register.go
  dragonfly/internal/item_internal/item.go
  dragonfly/item/bucket.go
  dragonfly/item/glass_bottle.go
  dragonfly/item/item.go
  dragonfly/item/potion.go
  dragonfly/item/potion/potion.go
  dragonfly/item/register.go
  dragonfly/player/player.go
Labels: awaiting review

#61 Implemented Farmland, Hoes, & Crops
  dragonfly/block/beetroot_seeds.go
  dragonfly/block/block.go
  dragonfly/block/break_info.go
  dragonfly/block/carrot.go
  dragonfly/block/cocoa_bean.go
  dragonfly/block/crop.go
  dragonfly/block/farmland.go
  dragonfly/block/glass_pane.go
  dragonfly/block/hashes.go
  dragonfly/block/kelp.go
  dragonfly/block/melon.go
  dragonfly/block/melon_seeds.go
  dragonfly/block/potato.go
  dragonfly/block/pumpkin_seeds.go
  dragonfly/block/register.go
  dragonfly/block/stained_glass_pane.go
  dragonfly/block/wheat_seeds.go
  dragonfly/internal/item_internal/item.go
  dragonfly/item/apple.go
  dragonfly/item/beetroot.go
  dragonfly/item/bonemeal.go
  dragonfly/item/hoe.go
  dragonfly/item/item.go
  dragonfly/item/melon_slice.go
  dragonfly/item/potion.go
  dragonfly/item/register.go
  dragonfly/item/wheat.go
  dragonfly/session/world.go
  dragonfly/world/particle/block.go
  go.mod
  go.sum
Labels: awaiting changes
