Repository df-mc/dragonfly, pull requests merged in 2022-12, with the labels that each got.

#707 Fix incorrect drops
  server/player/player.go
Labels: improvement

#705 Avoid saving unmodified chunks
  server/world/chunk/sub_chunk.go
  server/world/world.go
Labels: improvement

#696 Add ability to change xp with HandleBlockBreak event
  server/player/handler.go
  server/player/player.go
Labels: feature

#694 Support for multi-world providers
  server/player/data.go
  server/player/player.go
  server/player/playerdb/dimension.go
  server/player/playerdb/gamemode.go
  server/player/playerdb/json.go
  server/player/playerdb/leveldb.go
  server/player/provider.go
  server/server.go
Labels: feature, improvement

#677 pass a pointer in HandleFoodLoss to modify param "to"
  server/player/handler.go
  server/player/player.go
Labels: improvement
